Create hangman_new.py
someshnarwade/hangman pull request #4
Opened 2020-10-05 10:51 UTC by ankitranjan9

2020-10-05 17:27 UTC, someshnarwade requested changes
The formatting is very bad, that's why it's showing error while executing.
Please format it properly.

2020-10-06 13:23 UTC, ankitranjan9 commented
I have done the corrections and moved it to the other_solutions.
thank you

2020-10-07 14:26 UTC, someshnarwade requested changes
I've added comments for the changes required. If you have questions, please ask.

2020-10-07 14:26 UTC, someshnarwade commented on other_solutions/words.py
> +word_list = [    'wares',    'soup',    'mount',    'extend',    'brown',    'expert',    'tired',    'humidity',    'backpack',    'crust',    'dent',    'market',    'knock',    'smite',    'windy'
Instead of making a python file use a txt file and like 'word_list.txt'.

2020-10-07 14:26 UTC, someshnarwade commented on hangman_new.py
> +import randomfrom words import word_list
Delete this file.

2020-10-07 14:26 UTC, someshnarwade commented on other_solutions/README.md
> +you can this program using your command line.
Undo these changes

2020-10-07 14:26 UTC, someshnarwade commented on other_solutions/hang_man.py
> +import random
This works great.

2020-10-07 19:29 UTC, ankitranjan9 commented
I have deleted that file and changed words.py to words.txt. 
everything is done but not able to change the readme I have tried a lot.
please change it by yourself because from tomorrow my exams are going to start.
and please accept my PR this my 4th pr only.

2020-10-08 05:21 UTC, someshnarwade approved these changes
Approved

2020-10-08 05:21 UTC, merged